
import { makeStyles} from '@material-ui/core/styles';
export default makeStyles((theme) => ({
   
     bienvenido:{
        position: 'absolute',
        width: '120px',
        height: '24px',
        left: '653px',
        top: '252px',
        color: "#5974FB", 
        marginBottom:'10px',
        borderRadius: 'nullpx',
        fontFamily: 'Titillium Web',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: '22px',
        lineHeight: '24px',
        letterSpacing: '0.18px',
     },
     financiera:{
        position: 'absolute',
        height: '112px',
        width: '490px',
        left: '475px',
        top: '286px',
        borderRadius: 'nullpx',
        fontFamily: 'Titillium Web',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: '48px',
        lineHeight: '56px',
        textAlign: 'center',
        color: '#FFFFFF',
        marginBottom:'65px',
     },
     inputUsuario:{
        position: 'absolute',
        width: '450px',
        height: '56px',
        right: '0px',
        top: 'calc(50% - 56px/2 + 1px)',
        background: '#FFFFFF',
        borderRadius: '4px',
        marginBottom:'48px', 
        backgroundColor: '#FFFFFF',
     },
     labelInput:{
        position: 'absolute',
        height: '16px',
        width: '42px',
        left: '17px',
        top: '0px',
        borderRadius: 'nullpx',
        marginBottom:'5px',
        fontFamily: 'Titillium Web',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: '12px',
        lineHeight: '16px',
        letterSpacing: '0.4px',
        color: '#FFFFFF', 
     },
     inputPassword:{
        position: 'absolute',
        width: '450px',
        height: '56px',
        top:'21px',
        right: '0px',
        top: 'calc(50% - 56px/2 + 1px)',
        background: '#FFFFFF',
        borderRadius: '4px',
        marginBottom:'48px',
        backgroundColor: '#FFFFFF',
        border: '1px solid #E0E0E0',
        boxSizing: 'border-box',
        borderRadius: '4px',
        marginBottom:'39px',
         
     },
     trailingIcon: {
        width: '24px',
        height: '24px',
        margin: '0 0 1px',
        padding: '5px 1px 4px',
      },
      button:{
        height: '40px',
        width: '215px',
        left: '0px',
        top: '0px',
        position: 'absolute',
        right: '0%',
        bottom: '0%',
        backgroundColor: '#5974FB',
        borderRadius: '4px',
        marginBottom:'30px'
      },
      labelButton:{
        height: '16px',
        width: '187px',
        left: '15px',
        borderRadius: 'nullpx',
        position: 'absolute',
        left: '15px',
        right: '13px',
        top: 'calc(50% - 16px/2)',
        fontFamily: 'Titillium Web',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: '14px',
        lineHeight: '16px',
        textAlign: 'center',
        color: '#FFFFFF',
      },
      textOlvide:{
        position: 'absolute',
        height: '16px',
        left: '-27px',
        right: '-27px',
        top: 'calc(50% - 16px/2)',
        fontFamily: 'Titillium Web',
        fontStyle: 'normal',
        fontWeight: 'bold',
        fontSize: '14px',
        lineHeight: '16px',
        textAlign: 'center',
        color: '#FFFFFF',
        width: '128px',
        borderRadius: 'nullpx',

      },
      containerButton:{
        position: 'absolute',
        left: '42.5%',
        right: '42.57%',
        top: '64.65%',
        bottom: '31.45%',
        height: '40px',
        width: '215px',
        borderRadius: '0px',
    },
    textButtonContainer:{
        position: 'absolute',
        right: '47.5%',
        top: '70.31%',
        bottom: '25.78%',
        height: '40px',
        width: '74px',
        borderRadius: '0px'   
    },
    containerInput:{
    position: 'absolute',
    left: '34.38%',
    right: '34.38%',
    top: '53.32%',
    bottom: '37.3%',
    height: '96px',
    width: '450px',
    borderRadius: '0px'
},
containerInputNombre:{
    position: 'absolute',
    left: '34.38%',
    right: '34.38%',
    top: '43.16%',
    bottom: '47,46%',
    height: '96px',
    width: '450px',
    borderRadius: '0px'
},

body:{
    position: 'absolute',
    width: '1440px',
   //  width: '100%',
    height: '1024px',
    left: '0px',
    top: '0px',
    background: '#002563',
    borderRadius: '0px',
    
      }
}))